In [1]:
db =[["abhi",6,60],["rahul",2,20],["harry",7, 70],["krish",8,80]]

In [2]:
db

[['abhi', 6, 60], ['rahul', 2, 20], ['harry', 7, 70], ['krish', 8, 80]]

In [3]:
import numpy

In [4]:
ds =numpy.array(db)

In [5]:
ds

array([['abhi', '6', '60'],
       ['rahul', '2', '20'],
       ['harry', '7', '70'],
       ['krish', '8', '80']], dtype='<U5')

In [6]:
type(ds)

numpy.ndarray

In [7]:
type(db)

list

In [8]:
type(ds)

numpy.ndarray

In [9]:
marks =[60,20,70,80]

In [10]:
hours= [ 6,2,7,8]

In [11]:
marks

[60, 20, 70, 80]

In [12]:
hours

[6, 2, 7, 8]

In [13]:
marks  = numpy.array(marks)

In [14]:
hours = numpy.array(hours)

In [15]:
marks

array([60, 20, 70, 80])

In [16]:
hours

array([6, 2, 7, 8])

In [17]:
type(marks)

numpy.ndarray

In [18]:
jack_hours = 5

In [19]:
jack_marks = '?'

In [20]:
jack_marks

'?'

In [21]:
marks


array([60, 20, 70, 80])

In [32]:
hours = hours.reshape(-1,1)

In [23]:
import sklearn

In [24]:
sklearn.LinearREgression()

AttributeError: module 'sklearn' has no attribute 'LinearREgression'

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
mind = LinearRegression()

In [27]:
mind.fit(hours,marks) 

ValueError: Expected 2D array, got 1D array instead:
array=[6 2 7 8].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [28]:
hours

array([6, 2, 7, 8])

In [29]:
marks


array([60, 20, 70, 80])

In [31]:
mind.fit(hours,marks)

ValueError: Expected 2D array, got 1D array instead:
array=[6 2 7 8].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [33]:
hours

array([[6],
       [2],
       [7],
       [8]])

In [34]:
mind.fit(hours,marks)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [36]:
jack_marks = mind.predict([[jack_hours]])

In [37]:
jack_marks

array([50.])