In [77]:
import pandas as pd

In [78]:
d = pd.read_csv("50_Startups.csv")

In [79]:
d.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [80]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [81]:
y = d['Profit']

In [82]:
x = d[['R&D Spend', 'Administration', 'Marketing Spend', 'State']] 

In [83]:
x.shape

(50, 4)

In [84]:
y = y.values

In [85]:
type(y)

numpy.ndarray

In [86]:
type(x)

pandas.core.frame.DataFrame

In [87]:
from sklearn.linear_model import LinearRegression

In [108]:
model = LinearRegression()

In [109]:
model.fit(x,y)

LinearRegression()

In [110]:
d.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [107]:
model.coef_

AttributeError: 'LinearRegression' object has no attribute 'coef_'

In [91]:
#converting string to number: label encoding 
state = d["State"]

In [92]:
from sklearn.preprocessing import LabelEncoder 

In [93]:
#fit and transform 
state_le = LabelEncoder()

In [94]:
state = state_le.fit_transform(state)

In [95]:
state

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0])

In [96]:
type(x)

pandas.core.frame.DataFrame

In [97]:
x = x.values


In [98]:
type(x)

numpy.ndarray

In [105]:
x[: , 3]  = state

In [100]:
x

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1],
       [131876.9, 99814.71, 362861.36, 2],
       [134615.46, 147198.87, 127716.82, 0],
       [130298.13, 145530.06, 323876.68, 1],
       [120542.52, 148718.95, 311613.29, 2],
       [123334.88, 108679.17, 304981.62, 0],
       [101913.08, 110594.11, 229160.95, 1],
       [100671.96, 91790.61, 249744.55, 0],
       [93863.75, 127320.38, 249839.44, 1],
       [91992.39, 135495.07, 252664.93, 0],
       [119943.24, 156547.42, 256512.92, 1],
       [114523.61, 122616.84, 261776.23, 2],
       [78013.11, 121597.55, 264346.06, 0],
       [94657.16, 145077.58, 282574.31, 2],
       [91749.16, 114175.79, 294919.57, 1],
       [86419.7, 153514.11, 0.0, 2],
       [76253.86, 113867.3, 298664.47, 0],
       [78389.47, 153773.43, 299737.29, 2],
       [73994.56, 122782.75, 30331

In [112]:
state

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0])

In [113]:
model.fit(x, y)

LinearRegression()

In [114]:
model.coef_

array([  0.80575968,  -0.02682585,   0.02722767, -22.32057723])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
state_oh = OneHotEncoder()

In [ ]:
state_oh.fit_transform(state)

In [ ]:
state.shape

In [ ]:
state = state.reshape(-1,1)

In [ ]:
state_dummy = state_oh.fit_transform(state)

In [ ]:
state.shape

In [ ]:
state_dummy

In [ ]:
type(state_dummy)

In [ ]:
state_final = state_dummy.toarray()

In [ ]:
d

In [ ]:
type(state_final)

In [ ]:
type(x)

In [ ]:
x[: ,3] = state_final

In [ ]:
x.shape

In [ ]:
state_final.shape

In [ ]:
type(y)

In [ ]:
state

In [ ]:
state_final[: , 0:2]

In [ ]:
#to solve issue of dummy variable trap dummy variable trap
state_final = state_final[: , 0:2]

In [ ]:
x = x[: , 0:3 ]

In [ ]:
x

In [ ]:
state_final

In [ ]:
#we have to compbine state_final and x (add two arrays column wise)

In [ ]:
type(x)

In [ ]:
x.shape

In [ ]:
state_final.shape

In [ ]:
import numpy

In [ ]:
x_final = numpy.hstack((x,state_final))

In [ ]:
x_final

In [ ]:
model.fit(x_final,y)

In [ ]:
model.coef_

In [ ]:
d