In [1]:
import numpy

In [2]:
a = numpy.array([2,3,4,5])

In [3]:
a

array([2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a

array([2, 3, 4, 5])

In [6]:
a.shape

(4,)

In [7]:
b =numpy.array([[2,3],[2,6]])


In [8]:
b

array([[2, 3],
       [2, 6]])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.shape

(2, 2)

In [11]:
b

array([[2, 3],
       [2, 6]])

In [12]:
a

array([2, 3, 4, 5])

In [13]:
c

NameError: name 'c' is not defined

In [17]:
c =numpy.array([["abhi",12,90],["harry",45,34],["ravi",23,88],["erric",33,67]])

In [15]:
c

array([['abhi', '12', '90'],
       ['harry', '45', '34'],
       ['ravi', '23', '88']], dtype='<U5')

In [16]:
c.shape

(3, 3)

In [18]:
c

array([['abhi', '12', '90'],
       ['harry', '45', '34'],
       ['ravi', '23', '88'],
       ['erric', '33', '67']], dtype='<U5')

In [19]:
c.shape

(4, 3)

In [20]:
a[1]

3

In [21]:
c[1]

array(['harry', '45', '34'], dtype='<U5')

In [22]:
c[:,1]

array(['12', '45', '23', '33'], dtype='<U5')

In [25]:
c[:-1]

array([['abhi', '12', '90'],
       ['harry', '45', '34'],
       ['ravi', '23', '88']], dtype='<U5')

In [24]:
a

array([2, 3, 4, 5])

In [26]:
a.mean

<function ndarray.mean>

In [27]:
a.mean()

3.5

In [28]:
type(a)

numpy.ndarray

In [29]:
b

array([[2, 3],
       [2, 6]])

In [30]:
b.mean()

3.25

In [31]:
a

array([2, 3, 4, 5])

In [32]:
a.shape

(4,)

In [33]:
score

NameError: name 'score' is not defined

In [34]:
a[:1]

array([2])

In [35]:
a

array([2, 3, 4, 5])

In [36]:
a[:,-1]

IndexError: too many indices for array

In [37]:
a

array([2, 3, 4, 5])

In [38]:
a.shape

(4,)

In [39]:
b.shape

(2, 2)

In [40]:
c.shape

(4, 3)

In [41]:
c[:,-1]

array(['90', '34', '88', '67'], dtype='<U5')

In [42]:
c

array([['abhi', '12', '90'],
       ['harry', '45', '34'],
       ['ravi', '23', '88'],
       ['erric', '33', '67']], dtype='<U5')

In [43]:
score = c[:,-1]

In [44]:
score

array(['90', '34', '88', '67'], dtype='<U5')

In [45]:
type(score)

numpy.ndarray

In [46]:
score.shape

(4,)

In [47]:
score


array(['90', '34', '88', '67'], dtype='<U5')

In [48]:
score.mean()

TypeError: cannot perform reduce with flexible type

In [49]:
c

array([['abhi', '12', '90'],
       ['harry', '45', '34'],
       ['ravi', '23', '88'],
       ['erric', '33', '67']], dtype='<U5')

In [50]:
b

array([[2, 3],
       [2, 6]])

In [51]:
c.dtype

dtype('<U5')

In [52]:

a.dtype

dtype('int32')

In [53]:

score.mean()

TypeError: cannot perform reduce with flexible type

In [54]:
score.max()

TypeError: cannot perform reduce with flexible type

In [55]:
score.astype(int)

array([90, 34, 88, 67])

In [56]:
score

array(['90', '34', '88', '67'], dtype='<U5')

In [57]:
s = score.astype(int)

In [58]:
s

array([90, 34, 88, 67])

In [59]:
s.max()

90

In [60]:
s.mean()

69.75

In [61]:
s


array([90, 34, 88, 67])

In [62]:
c

array([['abhi', '12', '90'],
       ['harry', '45', '34'],
       ['ravi', '23', '88'],
       ['erric', '33', '67']], dtype='<U5')

In [63]:
c.dtype

dtype('<U5')

In [64]:
c.dtype ={ 'names':['StudentName','Phone','Score'],'formats':[numpy.str,numpy.int32,numpy.int32]}

ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype

In [65]:
c.dtype ={ 'names':['StudentName','Phone','Score'],'formats':[numpy.str,numpy.int32,numpy.int32]}

ValueError: When changing to a smaller dtype, its size must be a divisor of the size of original dtype

In [66]:
c

array([['abhi', '12', '90'],
       ['harry', '45', '34'],
       ['ravi', '23', '88'],
       ['erric', '33', '67']], dtype='<U5')

In [67]:
c

array([['abhi', '12', '90'],
       ['harry', '45', '34'],
       ['ravi', '23', '88'],
       ['erric', '33', '67']], dtype='<U5')

In [68]:
b

array([[2, 3],
       [2, 6]])

In [69]:
a

array([2, 3, 4, 5])

In [70]:
b

array([[2, 3],
       [2, 6]])

In [71]:
c

array([['abhi', '12', '90'],
       ['harry', '45', '34'],
       ['ravi', '23', '88'],
       ['erric', '33', '67']], dtype='<U5')

In [72]:
s


array([90, 34, 88, 67])

In [73]:
d =numpy.array([["abhi",1111,10],["jack",2222,20],["pop",3333,30],["eric",4444,40]])

In [74]:
d

array([['abhi', '1111', '10'],
       ['jack', '2222', '20'],
       ['pop', '3333', '30'],
       ['eric', '4444', '40']], dtype='<U4')

In [75]:
d.dtype ={ 'names':['StudentName','Phone','Score'],'formats':[numpy.str,numpy.int32,numpy.int32]}

In [76]:
d

array([[('',  97,  98), ('', 104, 105), ('',  49,  49), ('',  49,  49),
        ('',  49,  48), ('',   0,   0)],
       [('', 106,  97), ('',  99, 107), ('',  50,  50), ('',  50,  50),
        ('',  50,  48), ('',   0,   0)],
       [('', 112, 111), ('', 112,   0), ('',  51,  51), ('',  51,  51),
        ('',  51,  48), ('',   0,   0)],
       [('', 101, 114), ('', 105,  99), ('',  52,  52), ('',  52,  52),
        ('',  52,  48), ('',   0,   0)]],
      dtype=[('StudentName', '<U'), ('Phone', '<i4'), ('Score', '<i4')])

In [77]:
d[Marks]

NameError: name 'Marks' is not defined

In [78]:
d['Score']

array([[ 98, 105,  49,  49,  48,   0],
       [ 97, 107,  50,  50,  48,   0],
       [111,   0,  51,  51,  48,   0],
       [114,  99,  52,  52,  48,   0]])

In [79]:
h = numpy.array([1,2,3])

In [80]:
h

array([1, 2, 3])

In [81]:
t.dtype

NameError: name 't' is not defined

In [82]:
h.dtype

dtype('int32')

In [83]:
t.dtype = { 'names':['ID'],'formats':[numpy.int32]}

NameError: name 't' is not defined

In [84]:
 h.dtype = { 'names':['ID'],'formats':[numpy.int32]}

In [85]:
h

array([(1,), (2,), (3,)], dtype=[('ID', '<i4')])

In [86]:
h('ID')

TypeError: 'numpy.ndarray' object is not callable

In [87]:
h['ID']

array([1, 2, 3])

In [88]:
import pandas

In [89]:
dir(pandas)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17

In [90]:
import pandas

In [91]:
pandas.read_csv('book.csv')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2


In [92]:
pandas.read_csv('book.csv')

ParserError: Error tokenizing data. C error: Expected 2 fields in line 10, saw 3


In [93]:
import pandas

In [100]:
j=pandas.read_csv('book.csv')

ParserError: Error tokenizing data. C error: Expected 2 fields in line 10, saw 3


In [95]:
d

array([[('',  97,  98), ('', 104, 105), ('',  49,  49), ('',  49,  49),
        ('',  49,  48), ('',   0,   0)],
       [('', 106,  97), ('',  99, 107), ('',  50,  50), ('',  50,  50),
        ('',  50,  48), ('',   0,   0)],
       [('', 112, 111), ('', 112,   0), ('',  51,  51), ('',  51,  51),
        ('',  51,  48), ('',   0,   0)],
       [('', 101, 114), ('', 105,  99), ('',  52,  52), ('',  52,  52),
        ('',  52,  48), ('',   0,   0)]],
      dtype=[('StudentName', '<U'), ('Phone', '<i4'), ('Score', '<i4')])

In [96]:
h

array([(1,), (2,), (3,)], dtype=[('ID', '<i4')])

In [97]:
h['score']

ValueError: no field of name score

In [98]:
h['Score']

ValueError: no field of name Score

In [99]:
h['ID']

array([1, 2, 3])

In [101]:
j

NameError: name 'j' is not defined

In [102]:
import pandas

In [103]:
l = pandas.read_csv('book.csv')

ParserError: Error tokenizing data. C error: Expected 2 fields in line 10, saw 3
