In [1]:
import pandas

In [7]:
dataset = pandas.read_csv('book1.csv')

In [8]:
dataset

Experience  Salary
0         1.1    2000
1         3.0    3000
2         5.0    6500
3         2.0    2050
4         4.0    6422
5        10.0  242432

In [9]:
dataset


Experience  Salary
0         1.1    2000
1         3.0    3000
2         5.0    6500
3         2.0    2050
4         4.0    6422
5        10.0  242432

In [11]:
dataset.columns

Index(['Experience', 'Salary'], dtype='object')

In [12]:
y = dataset['Salary']

In [14]:
x= dataset['Experience']

In [16]:
type(x)

pandas.core.series.Series

In [18]:
x = x.values

In [20]:
x = x.reshape(-1,1)

In [21]:
type(x)

numpy.ndarray

In [22]:
x=x.reshape(-1,1)

In [23]:
x

array([[ 1.1],
       [ 3. ],
       [ 5. ],
       [ 2. ],
       [ 4. ],
       [10. ]])

In [24]:
from sklearn.linear_model import LinearRegression

ModuleNotFoundError: No module named 'sklearn'

In [26]:
from sklearn.linear_model import LinearRegression


In [27]:
model = LinearRegression()

In [28]:
model.fit(x,y)

LinearRegression()

In [29]:
model.predict([[1.5]])

array([1.5])

In [33]:
model.predict([[780]])

array([780.])

In [34]:
model.coef_

array([1.])