In [1]:
import pandas

In [4]:
dataset = pandas.read_csv('book1.csv')

In [5]:
dataset

Experience  Salary
0         1.1    2067
1         3.0    3052
2         5.0    6587
3         2.0    2099
4         4.0    6422
5        10.0  242432
6        11.0  271203

In [6]:
dataset.columns

Index(['Experience', 'Salary'], dtype='object')

In [8]:
y = dataset['Salary']

In [9]:
x= dataset['Experience']

In [10]:
type(x)

pandas.core.series.Series

In [11]:
x = x.values

In [12]:
x=x.reshape(-1,1)

In [13]:
type(x)

numpy.ndarray

In [14]:
x

array([[ 1.1],
       [ 3. ],
       [ 5. ],
       [ 2. ],
       [ 4. ],
       [10. ],
       [11. ]])

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model = LinearRegression()

In [17]:
model.fit(x,y)

LinearRegression()

In [18]:
model.predict([[10.5]])

array([238182.7980516])

In [19]:
model.coef_

array([30305.28305779])

In [20]:
model.predict([[3.3]])

array([19984.76003554])