In [1]:
import numpy as np


In [4]:
a = [1,2,3]
type(a)

list

In [5]:
b = np.array(a)

In [6]:
type(b)

numpy.ndarray

In [7]:
print(type(b))

<class 'numpy.ndarray'>


In [15]:
#list can have different types of values
a = [1,2,3,'5',4,6,]
b = np.array(a,dtype=int)
type(b)
print(b)

[1 2 3 5 4 6]


In [16]:
a = [1,2,3,'5',4,6,]
b = np.array(a *2,dtype=int)
type(b)
print(b)

[1 2 3 5 4 6 1 2 3 5 4 6]


In [23]:
b = np.zeros(9, dtype=int)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
b = np.ones(9, dtype=int)
b

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [26]:
b = np.ones((2,2), dtype=int)
b

array([[1, 1],
       [1, 1]])

In [28]:
n = np.full(3,4)
n

array([4, 4, 4])

In [44]:
n = np.empty((2,3))
n

array([[4.24399158e-314, 1.06099790e-313, 1.27319747e-313],
       [4.24399158e-314, 1.06099790e-313, 1.27319747e-313]])

In [43]:
n = np.empty((2,3))
n

array([[4.24399158e-314, 1.06099790e-313, 1.27319747e-313],
       [4.24399158e-314, 1.06099790e-313, 1.27319747e-313]])

In [48]:
b = np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])